default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: recruit_web_development

test:
  <<: *default
  database: recruit_web_test

production:
  <<: *default
  database: recruit_web_production
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:host] %>